dj_db2/urls.py
from django.contrib import admin
from django.urls import path

from m2m.views import articles_list
from school.views import students_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('m2m/', articles_list, name='m2m'),
    path('school/', students_list, name='school'),
]

m2m/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=256, verbose_name='Название')
    text = models.TextField(verbose_name='Текст')
    published_at = models.DateTimeField(verbose_name='Дата публикации')
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение', )
    sections = models.ManyToManyField('Section', through='Relations', related_name='art')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.title


class Section(models.Model):
    name = models.CharField(max_length=64, verbose_name='Секция', null=False)

    class Meta:
        verbose_name = 'Секция'
        verbose_name_plural = 'Секции'

    def __str__(self):
        return self.name


class Relations(models.Model):
    articles = models.ForeignKey(Article, on_delete=models.CASCADE)
    sections = models.ForeignKey(Section, on_delete=models.CASCADE)
    is_main = models.BooleanField(verbose_name='Основная секция')

    class Meta:
        verbose_name = 'Секция в статье'
        verbose_name_plural = 'Секции в статье'
        ordering = ["-is_main", "sections__name"]

school/models.py
from django.db import models


class Teacher(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    subject = models.CharField(max_length=10, verbose_name='Предмет')

    class Meta:
        verbose_name = 'Учитель'
        verbose_name_plural = 'Учителя'

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    teacher = models.ManyToManyField(Teacher, related_name='students')
    group = models.CharField(max_length=10, verbose_name='Класс')

    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'

    def __str__(self):
        return self.name

m2m/views.py
from django.views.generic import ListView
from django.shortcuts import render

from m2m.models import Article, Section, Relations


def articles_list(request):
    articles = Article.objects.all().prefetch_related('sections')
    template = 'm2m/news.html'
    context = {'object_list': articles}

    # используйте этот параметр для упорядочивания результатов
    # https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.order_by
    ordering = '-published_at'

    return render(request, template, context)

school/views.py
from django.views.generic import ListView
from django.shortcuts import render

from .models import Student


def students_list(request):
    students = Student.objects.all().prefetch_related('teacher')
    template = 'school/students_list.html'
    context = {'students': students}

    # используйте этот параметр для упорядочивания результатов
    # https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.order_by
    ordering = 'group'

    return render(request, template, context)

m2m/templates/m2m/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
      <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- Bootstrap core CSS -->
    <link href="{% static  "css/bootstrap.min.css"  %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static  "css/3-col-portfolio.css" %}" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
      <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Будь в курсе событий</a>
      </div>
    </nav>

    <div class="container">{% block content %}{% endblock %}</div>

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>
      <!-- Bootstrap core JavaScript -->
    <script src="{% static  "js/jquery.min.js" %}"></script>
  </body>
</html>

m2m/templates/m2m/news.html
{% extends "m2m/base.html" %}
{% load static %}

{% block title %}Новости{% endblock %}
{% block content %}
<div class="row">
    {% for article in object_list %}
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="{% get_static_prefix %}media/{{ article.image }}" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">{{ article.title }}</a>
                </h4>
                <p class="card-text">{{ article.text }}</p>
                {% for scope in article.relations_set.all %}
                <span class="badge {% if scope.is_main %}badge-primary{% else %}badge-secondary{% endif %}">{{ scope.sections.name }}</span>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

school/templates/school/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
      <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- Bootstrap core CSS -->
    <link href="{% static  "css/bootstrap.min.css"  %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static  "css/3-col-portfolio.css" %}" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
      <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Список учеников школы</a>
      </div>
    </nav>

    <div class="container">{% block content %}{% endblock %}</div>

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>
      <!-- Bootstrap core JavaScript -->
    <script src="{% static  "js/jquery.min.js" %}"></script>
  </body>
</html>

school/templates/school/students_list.html
{% extends "school/base.html" %}
{% load static %}

{% block title %}Список учеников{% endblock %}
{% block content %}
<div class="row">
    <ul>
        {% for student in students %}
        <li>{{ student.name }} {{ student.group }} <br>
            Преподаватели:
            <ul>
                {% for teacher in student.teacher.all %}
                <li>{{ teacher.name }} - {{ teacher.subject }}</li>
                {% endfor %}
            </ul>
            <hr>
            {% endfor %}
    </ul>
</div>
{% endblock %}